from pathlib import Path

from services.resume_matcher import analyze_resume_match


BASE_DIR = Path(__file__).resolve().parent

RESUME_PATH = BASE_DIR / "data" / "sample_resume.txt"
JOB_DESCRIPTION_PATH = BASE_DIR / "data" / "sample_job_description.txt"
OUTPUT_PATH = BASE_DIR / "outputs" / "careerfit_match_report.md"


def read_text_file(file_path):
    """
    Reads text from a file.

    Args:
        file_path (Path): The path to the text file.

    Returns:
        str: The file content as text.

    Raises:
        FileNotFoundError: If the file does not exist.
    """
    if not file_path.exists():
        raise FileNotFoundError(f"File not found: {file_path}")

    return file_path.read_text(encoding="utf-8")


def save_report(report_text):
    """
    Saves the AI-generated report to the outputs folder.

    Args:
        report_text (str): The report generated by CareerFit AI.
    """
    OUTPUT_PATH.parent.mkdir(exist_ok=True)
    OUTPUT_PATH.write_text(report_text, encoding="utf-8")


def main():
    """
    Runs the CareerFit AI resume/job matching workflow.
    """
    print("CareerFit AI is analyzing the resume against the job description...\n")

    resume_text = read_text_file(RESUME_PATH)
    job_description_text = read_text_file(JOB_DESCRIPTION_PATH)

    report = analyze_resume_match(
        resume_text=resume_text,
        job_description_text=job_description_text,
    )

    save_report(report)

    print(report)
    print(f"\nReport saved to: {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
