import argparse
from pathlib import Path

from services.resume_matcher import analyze_resume_match


BASE_DIR = Path(__file__).resolve().parent

DEFAULT_RESUME_PATH = BASE_DIR / "data" / "sample_resume.txt"
DEFAULT_JOB_DESCRIPTION_PATH = BASE_DIR / "data" / "sample_job_description.txt"
DEFAULT_OUTPUT_PATH = BASE_DIR / "outputs" / "careerfit_match_report.md"


def read_text_file(file_path):
    """
    Reads text from a file.

    Args:
        file_path (Path): The path to the text file.

    Returns:
        str: The file content as text.

    Raises:
        FileNotFoundError: If the file does not exist.
    """
    if not file_path.exists():
        raise FileNotFoundError(f"File not found: {file_path}")

    return file_path.read_text(encoding="utf-8")


def save_report(report_text, output_path):
    """
    Saves the AI-generated report to the selected output path.

    Args:
        report_text (str): The report generated by CareerFit AI.
        output_path (Path): The file path where the report should be saved.
    """
    output_path.parent.mkdir(exist_ok=True)
    output_path.write_text(report_text, encoding="utf-8")


def parse_args():
    """
    Parses command-line arguments for the CareerFit AI CLI app.

    Returns:
        argparse.Namespace: The parsed command-line arguments.
    """
    parser = argparse.ArgumentParser(
        description="CareerFit AI - Resume and Job Description Match Assistant"
    )

    parser.add_argument(
        "--resume",
        default=DEFAULT_RESUME_PATH,
        help="Path to the resume text file.",
    )

    parser.add_argument(
        "--job",
        default=DEFAULT_JOB_DESCRIPTION_PATH,
        help="Path to the job description text file.",
    )

    parser.add_argument(
        "--output",
        default=DEFAULT_OUTPUT_PATH,
        help="Path where the match report should be saved.",
    )

    return parser.parse_args()


def main():
    """
    Runs the CareerFit AI resume/job matching workflow.
    """
    args = parse_args()

    resume_path = Path(args.resume)
    job_description_path = Path(args.job)
    output_path = Path(args.output)

    print("CareerFit AI is analyzing the resume against the job description...\n")
    print(f"Resume file: {resume_path}")
    print(f"Job description file: {job_description_path}")
    print(f"Output file: {output_path}\n")

    resume_text = read_text_file(resume_path)
    job_description_text = read_text_file(job_description_path)

    report = analyze_resume_match(
        resume_text=resume_text,
        job_description_text=job_description_text,
    )

    save_report(report, output_path)

    print(report)
    print(f"\nReport saved to: {output_path}")


if __name__ == "__main__":
    main()